# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=2)),
                ('review', models.CharField(max_length=200)),
                ('date', models.DateField(max_length=25)),
                ('totalproduct', models.CharField(max_length=10)),
            ],
        ),
    ]
